<?php
/**
 * LW Firewall — MU-Plugin Worker
 *
 * This file is automatically installed to mu-plugins/ by the LW Firewall plugin.
 * It runs early (before template_redirect) to block bots and rate-limit requests.
 *
 * DO NOT EDIT THIS FILE DIRECTLY — it will be overwritten on plugin activation.
 *
 * Failure modes are deliberately silent: the worker should NEVER take a site
 * down. If anything looks wrong (PHP too old, plugin files missing, version
 * mismatch with the main plugin, throwable during execution), it bails out
 * and lets the main plugin show an admin notice + reinstall itself.
 *
 * Emergency kill-switch: define( 'LW_FIREWALL_DISABLE_WORKER', true ); in
 * wp-config.php to neutralize the worker completely.
 *
 * @package LightweightPlugins\Firewall
 * @version 1.5.8
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'LW_FIREWALL_WORKER_VERSION', '1.5.8' );

// Emergency kill-switch — wp-config.php may neutralize the worker.
if ( defined( 'LW_FIREWALL_DISABLE_WORKER' ) && LW_FIREWALL_DISABLE_WORKER ) {
	return;
}

// Hard PHP requirement — bail silently on anything older than 8.2. This is a
// standalone MU-plugin file that may run on older PHP than the main plugin
// requires, so the guard is real at runtime even though static analysis
// (which assumes >= 8.2) sees it as always false.
// @phpstan-ignore smaller.alwaysFalse
if ( PHP_VERSION_ID < 80200 ) {
	return;
}

( static function (): void {
	try {
		$autoload    = WP_PLUGIN_DIR . '/lw-firewall/includes/';
		$plugin_main = WP_PLUGIN_DIR . '/lw-firewall/lw-firewall.php';

		// Required files manifest — every class the worker may instantiate.
		$required = [
			'Options.php',
			'IpDetector.php',
			'IpSubject.php',
			'Logger.php',
			'helpers.php',
			'Rules/RateLimiter.php',
			'Rules/IpMatcher.php',
			'Rules/BotBlocker.php',
			'Rules/AutoBanner.php',
			'Rules/NotFoundTracker.php',
			'Geo/GeoDetector.php',
			'Geo/RangeIndex.php',
			'Geo/RangeIndex6.php',
			'Storage/StorageInterface.php',
			'Storage/ApcuStorage.php',
			'Storage/RedisStorage.php',
			'Storage/FileStorage.php',
		];

		foreach ( $required as $rel ) {
			if ( ! file_exists( $autoload . $rel ) ) {
				return;
			}
		}

		// Version guard — refuse to run if the main plugin and worker drifted apart.
		// Prevents the post-update race where the old worker runs against new classes.
		if ( file_exists( $plugin_main ) && function_exists( 'get_file_data' ) ) {
			$data = get_file_data( $plugin_main, [ 'Version' => 'Version' ] );
			if ( ! empty( $data['Version'] ) && LW_FIREWALL_WORKER_VERSION !== $data['Version'] ) {
				return;
			}
		}

		// Register autoloader.
		spl_autoload_register(
			static function ( string $class_name ) use ( $autoload ): void {
				$prefix = 'LightweightPlugins\\Firewall\\';

				if ( ! str_starts_with( $class_name, $prefix ) ) {
					return;
				}

				$relative = substr( $class_name, strlen( $prefix ) );
				$file     = $autoload . str_replace( '\\', '/', $relative ) . '.php';

				if ( file_exists( $file ) ) {
					require_once $file;
				}
			}
		);

		// Include shared helpers (not the main plugin file — that would bootstrap the plugin).
		if ( ! function_exists( 'lw_firewall_resolve_storage' ) ) {
			require_once $autoload . 'helpers.php';
		}

		add_action(
			'muplugins_loaded',
			static function (): void {
				try {
					if ( ! class_exists( \LightweightPlugins\Firewall\Options::class ) ) {
						return;
					}

					$options = \LightweightPlugins\Firewall\Options::get_all();

					// Health handshake: the main plugin can otherwise only see
					// that the file exists and carries a matching version
					// constant — which the worker defines before it has proved
					// it can load anything. A renamed plugin directory left it
					// looking current while it silently did nothing.
					if ( ! get_transient( 'lw_firewall_worker_alive' ) ) {
						set_transient( 'lw_firewall_worker_alive', time(), DAY_IN_SECONDS );
					}

					if ( empty( $options['enabled'] ) ) {
						return;
					}

					$ip = \LightweightPlugins\Firewall\IpDetector::get_ip();

					// --- Server/localhost: always skip ---
					if ( lw_firewall_is_server_ip( $ip ) ) {
						return;
					}

					// --- IP Whitelist: skip all checks ---
					$whitelist = (array) ( $options['ip_whitelist'] ?? [] );

					if ( ! empty( $whitelist ) && \LightweightPlugins\Firewall\Rules\IpMatcher::matches( $ip, $whitelist ) ) {
						return;
					}

					// --- IP Blacklist: block immediately ---
					$blacklist = (array) ( $options['ip_blacklist'] ?? [] );

					if ( ! empty( $blacklist ) && \LightweightPlugins\Firewall\Rules\IpMatcher::matches( $ip, $blacklist ) ) {
						lw_firewall_log( $options, $ip, 'ip_blacklisted' );
						lw_firewall_block_403();
					}

					// --- Geo blocking ---
					if ( ! empty( $options['geo_enabled'] ) ) {
						$blocked_countries = (array) ( $options['blocked_countries'] ?? [] );

						if ( ! empty( $blocked_countries )
						&& \LightweightPlugins\Firewall\Geo\GeoDetector::is_blocked( $ip, $blocked_countries )
						) {
							lw_firewall_log( $options, $ip, 'geo_blocked' );
							lw_firewall_block_403();
						}
					}

					$storage = lw_firewall_resolve_storage( $options['storage'] ?? 'auto' );

					// --- Ban check ---
					// Unconditional while the firewall is on. Gating this on the
					// auto-ban and login-lockout toggles left every other producer
					// — registration spam, password-reset floods, a manual CLI or
					// admin ban — writing a ban key that nothing ever read: the
					// admin listed the address as banned while it browsed the site
					// freely.
					$banner = new \LightweightPlugins\Firewall\Rules\AutoBanner( $storage );

					if ( $banner->is_banned( $ip ) ) {
						lw_firewall_log( $options, $ip, 'auto_banned' );
						\LightweightPlugins\Firewall\Rules\AutoBanner::block();
					}

					// --- 404 flood check (counter is tracked in Plugin.php) ---
					if ( ! empty( $options['protect_404'] ) ) {
						$tracker = new \LightweightPlugins\Firewall\Rules\NotFoundTracker( $storage );

						if ( $tracker->is_flooding( $ip ) ) {
							lw_firewall_log( $options, $ip, 'rate_limited_404' );
							\LightweightPlugins\Firewall\Rules\RateLimiter::too_many();
						}
					}

					// --- Bot blocking (all requests) ---
					// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
					$user_agent = $_SERVER['HTTP_USER_AGENT'] ?? '';

					if ( \LightweightPlugins\Firewall\Rules\BotBlocker::is_blocked( $user_agent ) ) {
						lw_firewall_log( $options, $ip, 'bot_blocked' );
						\LightweightPlugins\Firewall\Rules\BotBlocker::block();
					}

					// --- Detect request type ---
					// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
					$request_uri               = $_SERVER['REQUEST_URI'] ?? '';
					[ $reason, $custom_limit ] = lw_firewall_detect_type( $request_uri, $options );

					if ( null === $reason ) {
						return;
					}

					// --- Rate limiting ---
					// Signed-in users get a SEPARATE, higher-limit bucket on the
					// REST/filter endpoints (where dashboards fire request bursts),
					// not a full exemption. login/xmlrpc/cron stay fully throttled
					// regardless of any cookie, so a forged logged-in cookie cannot
					// disable brute-force or abuse protection — at worst it raises
					// the limit on two endpoints, and abuse there is still recorded
					// for auto-ban.
					$logged_in = lw_firewall_login_exempt_reason( $reason ) && lw_firewall_has_login_cookie();

					// Counted per subject: an IPv6 client's whole /64, so rotating
					// addresses inside it does not reset the count.
					$subject = \LightweightPlugins\Firewall\IpSubject::of( $ip );

					if ( $logged_in ) {
						$rl_key   = $reason . '_li_' . $subject;
						$rl_limit = lw_firewall_loggedin_limit( $custom_limit, $options );
					} else {
						$rl_key   = $reason . '_' . $subject;
						$rl_limit = $custom_limit;
					}

					$limiter = new \LightweightPlugins\Firewall\Rules\RateLimiter( $storage );

					if ( ! $limiter->is_allowed_key( $rl_key, $rl_limit ) ) {
						lw_firewall_log( $options, $ip, 'rate_limited_' . $reason );

						// Record violation for auto-ban.
						if ( ! empty( $options['auto_ban_enabled'] ) ) {
							$banner = new \LightweightPlugins\Firewall\Rules\AutoBanner( $storage );
							$banner->record_violation( $ip );
						}

						// Filter uses configured action; everything else gets 429.
						if ( 'filter' === $reason ) {
							\LightweightPlugins\Firewall\Rules\RateLimiter::limit();
						} else {
							\LightweightPlugins\Firewall\Rules\RateLimiter::too_many();
						}
					}
				} catch ( \Throwable $e ) {
					if ( defined( 'WP_DEBUG' ) && WP_DEBUG && defined( 'WP_DEBUG_LOG' ) && WP_DEBUG_LOG ) {
						error_log( 'LW Firewall worker (runtime): ' . $e->getMessage() ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
					}
				}
			},
			1
		);
	} catch ( \Throwable $e ) {
		if ( defined( 'WP_DEBUG' ) && WP_DEBUG && defined( 'WP_DEBUG_LOG' ) && WP_DEBUG_LOG ) {
			error_log( 'LW Firewall worker (bootstrap): ' . $e->getMessage() ); // phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log
		}
	}
} )();
