<?php
/**
 * LW Firewall — MU-Plugin Worker
 *
 * This file is automatically installed to mu-plugins/ by the LW Firewall plugin.
 * It runs early (before template_redirect) to block bots and rate-limit requests.
 *
 * DO NOT EDIT THIS FILE DIRECTLY — it will be overwritten on plugin activation.
 *
 * @package LightweightPlugins\Firewall
 * @version 1.1.6
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

define( 'LW_FIREWALL_WORKER_VERSION', '1.1.6' );

( static function (): void {
	$plugin_path = WP_PLUGIN_DIR . '/lw-firewall/';
	$autoload    = $plugin_path . 'includes/';

	if ( ! file_exists( $autoload . 'Options.php' ) ) {
		return;
	}

	// Register autoloader.
	spl_autoload_register(
		static function ( string $class_name ) use ( $autoload ): void {
			$prefix = 'LightweightPlugins\\Firewall\\';

			if ( ! str_starts_with( $class_name, $prefix ) ) {
				return;
			}

			$relative = substr( $class_name, strlen( $prefix ) );
			$file     = $autoload . str_replace( '\\', '/', $relative ) . '.php';

			if ( file_exists( $file ) ) {
				require_once $file;
			}
		}
	);

	// Include shared helpers (not the main plugin file — that would bootstrap the plugin).
	if ( ! function_exists( 'lw_firewall_resolve_storage' ) ) {
		$helpers = $autoload . 'helpers.php';
		if ( file_exists( $helpers ) ) {
			require_once $helpers;
		}
	}

	add_action(
		'muplugins_loaded',
		static function (): void {
			$options = \LightweightPlugins\Firewall\Options::get_all();

			if ( empty( $options['enabled'] ) ) {
				return;
			}

			$ip = \LightweightPlugins\Firewall\IpDetector::get_ip();

			// --- Server/localhost: always skip ---
			if ( lw_firewall_is_server_ip( $ip ) ) {
				return;
			}

			// --- IP Whitelist: skip all checks ---
			$whitelist = (array) ( $options['ip_whitelist'] ?? [] );

			if ( ! empty( $whitelist ) && \LightweightPlugins\Firewall\Rules\IpMatcher::matches( $ip, $whitelist ) ) {
				return;
			}

			// --- IP Blacklist: block immediately ---
			$blacklist = (array) ( $options['ip_blacklist'] ?? [] );

			if ( ! empty( $blacklist ) && \LightweightPlugins\Firewall\Rules\IpMatcher::matches( $ip, $blacklist ) ) {
				lw_firewall_log( $options, $ip, 'ip_blacklisted' );
				lw_firewall_block_403();
			}

			$storage = lw_firewall_resolve_storage( $options['storage'] ?? 'auto' );

			// --- Auto-ban check ---
			if ( ! empty( $options['auto_ban_enabled'] ) ) {
				$banner = new \LightweightPlugins\Firewall\Rules\AutoBanner( $storage );

				if ( $banner->is_banned( $ip ) ) {
					lw_firewall_log( $options, $ip, 'auto_banned' );
					\LightweightPlugins\Firewall\Rules\AutoBanner::block();
				}
			}

			// --- 404 flood check (counter is tracked in Plugin.php) ---
			if ( ! empty( $options['protect_404'] ) ) {
				$tracker = new \LightweightPlugins\Firewall\Rules\NotFoundTracker( $storage );

				if ( $tracker->is_flooding( $ip ) ) {
					lw_firewall_log( $options, $ip, 'rate_limited_404' );
					\LightweightPlugins\Firewall\Rules\RateLimiter::too_many();
				}
			}

			// --- Bot blocking (all requests) ---
			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
			$user_agent = $_SERVER['HTTP_USER_AGENT'] ?? '';

			if ( \LightweightPlugins\Firewall\Rules\BotBlocker::is_blocked( $user_agent ) ) {
				lw_firewall_log( $options, $ip, 'bot_blocked' );
				\LightweightPlugins\Firewall\Rules\BotBlocker::block();
			}

			// --- Detect request type ---
			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
			$request_uri               = $_SERVER['REQUEST_URI'] ?? '';
			[ $reason, $custom_limit ] = lw_firewall_detect_type( $request_uri, $options );

			if ( null === $reason ) {
				return;
			}

			// --- Rate limiting ---
			$limiter = new \LightweightPlugins\Firewall\Rules\RateLimiter( $storage );

			if ( ! $limiter->is_allowed_key( $reason . '_' . $ip, $custom_limit ) ) {
				lw_firewall_log( $options, $ip, 'rate_limited_' . $reason );

				// Record violation for auto-ban.
				if ( ! empty( $options['auto_ban_enabled'] ) ) {
					$banner = new \LightweightPlugins\Firewall\Rules\AutoBanner( $storage );
					$banner->record_violation( $ip );
				}

				// Filter uses configured action; everything else gets 429.
				if ( 'filter' === $reason ) {
					\LightweightPlugins\Firewall\Rules\RateLimiter::limit();
				} else {
					\LightweightPlugins\Firewall\Rules\RateLimiter::too_many();
				}
			}
		},
		1
	);
} )();

/**
 * Detect request type from URI.
 *
 * Returns an array of [reason, custom_limit]. The custom_limit is null unless
 * a filter param entry specifies one (e.g. "filter_|30").
 *
 * @param string               $uri     Request URI.
 * @param array<string, mixed> $options Plugin options.
 * @return array{0: string|null, 1: int|null}
 */
function lw_firewall_detect_type( string $uri, array $options ): array {
	if ( str_contains( $uri, '/wp-cron.php' ) && ! empty( $options['protect_cron'] ) ) {
		return [ 'cron', null ];
	}

	if ( str_contains( $uri, '/xmlrpc.php' ) && ! empty( $options['protect_xmlrpc'] ) ) {
		return [ 'xmlrpc', null ];
	}

	if ( str_contains( $uri, '/wp-login.php' ) && ! empty( $options['protect_login'] ) ) {
		return [ 'login', null ];
	}

	if ( str_contains( $uri, '/wp-json/' ) && ! empty( $options['protect_rest_api'] ) ) {
		return [ 'rest', null ];
	}

	// WooCommerce filter parameter detection.
	// Entries may include a custom rate limit: "filter_|30".
	// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
	$query_string  = $_SERVER['QUERY_STRING'] ?? '';
	$filter_params = $options['filter_params'] ?? [ 'filter_|30', 'query_type_|30' ];

	if ( '' !== $query_string ) {
		$matched      = false;
		$custom_limit = null;

		foreach ( $filter_params as $entry ) {
			$parts  = explode( '|', (string) $entry, 2 );
			$prefix = $parts[0];

			if ( str_contains( $query_string, $prefix ) ) {
				$matched = true;

				// Use the lowest custom limit if multiple params match.
				if ( isset( $parts[1] ) && is_numeric( $parts[1] ) ) {
					$limit        = (int) $parts[1];
					$custom_limit = ( null === $custom_limit ) ? $limit : min( $custom_limit, $limit );
				}
			}
		}

		if ( $matched ) {
			return [ 'filter', $custom_limit ];
		}
	}

	return [ null, null ];
}

/**
 * Log a firewall event if logging is enabled.
 *
 * @param array<string, mixed> $options Plugin options.
 * @param string               $ip      Client IP.
 * @param string               $reason  Block reason.
 */
function lw_firewall_log( array $options, string $ip, string $reason ): void {
	if ( empty( $options['log_enabled'] ) ) {
		return;
	}

	\LightweightPlugins\Firewall\Logger::log(
		[
			'ip'     => $ip,
			'reason' => $reason,
			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
			'ua'     => substr( (string) ( $_SERVER['HTTP_USER_AGENT'] ?? '' ), 0, 200 ),
			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
			'url'    => sanitize_url( wp_unslash( $_SERVER['REQUEST_URI'] ?? '' ) ),
		]
	);
}

/**
 * Check if the IP belongs to the server itself.
 *
 * Matches localhost, server address, and the site domain's resolved IP
 * (cached for 5 minutes to avoid DNS lookups on every request).
 *
 * @param string $ip Client IP to check.
 * @return bool
 */
function lw_firewall_is_server_ip( string $ip ): bool {
	// Localhost.
	if ( '127.0.0.1' === $ip || '::1' === $ip ) {
		return true;
	}

	// Server's own IP.
	// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
	$server_addr = $_SERVER['SERVER_ADDR'] ?? '';
	if ( '' !== $server_addr && $server_addr === $ip ) {
		return true;
	}

	// Domain resolved IP (cached in transient).
	$domain_ip = get_transient( 'lw_firewall_domain_ip' );
	if ( false === $domain_ip ) {
		// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
		$host     = $_SERVER['SERVER_NAME'] ?? wp_parse_url( home_url(), PHP_URL_HOST );
		$resolved = (string) gethostbyname( (string) $host );
		// Only cache if resolution succeeded (not same as input).
		$domain_ip = ( $resolved !== $host ) ? $resolved : '';
		set_transient( 'lw_firewall_domain_ip', $domain_ip, 300 );
	}

	if ( '' !== $domain_ip && $domain_ip === $ip ) {
		return true;
	}

	return false;
}

/**
 * Send 403 Forbidden and exit.
 */
function lw_firewall_block_403(): void {
	if ( ! headers_sent() ) {
		header( 'HTTP/1.1 403 Forbidden' );
		header( 'Content-Type: text/plain; charset=utf-8' );
		header( 'Cache-Control: no-store, no-cache' );
	}

	echo 'Access denied.';
	exit;
}
