<?php
/**
 * LW Firewall — MU-Plugin Worker
 *
 * This file is automatically installed to mu-plugins/ by the LW Firewall plugin.
 * It runs early (before template_redirect) to block bots and rate-limit filter requests.
 *
 * DO NOT EDIT THIS FILE DIRECTLY — it will be overwritten on plugin activation.
 *
 * @package LightweightPlugins\Firewall
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

( static function (): void {
	// Locate the main plugin.
	$plugin_path = WP_PLUGIN_DIR . '/lw-firewall/';
	$autoload    = $plugin_path . 'includes/';

	// Bail if the main plugin is not present.
	if ( ! file_exists( $autoload . 'Options.php' ) ) {
		return;
	}

	// Register autoloader for the plugin namespace.
	spl_autoload_register(
		static function ( string $class_name ) use ( $autoload ): void {
			$prefix = 'LightweightPlugins\\Firewall\\';

			if ( ! str_starts_with( $class_name, $prefix ) ) {
				return;
			}

			$relative = substr( $class_name, strlen( $prefix ) );
			$file     = $autoload . str_replace( '\\', '/', $relative ) . '.php';

			if ( file_exists( $file ) ) {
				require_once $file;
			}
		}
	);

	// Run protection on muplugins_loaded — before any theme or plugin code.
	add_action(
		'muplugins_loaded',
		static function (): void {
			// Check if firewall is enabled.
			$options = \LightweightPlugins\Firewall\Options::get_all();

			if ( empty( $options['enabled'] ) ) {
				return;
			}

			// Only process requests that contain filter parameters in the query string.
			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- Raw query string checked for substring match only.
			$query_string = $_SERVER['QUERY_STRING'] ?? '';

			if ( '' === $query_string ) {
				return;
			}

			$filter_params = $options['filter_params'] ?? [ 'filter_', 'query_type_' ];
			$has_filter    = false;

			foreach ( $filter_params as $prefix ) {
				if ( str_contains( $query_string, $prefix ) ) {
					$has_filter = true;
					break;
				}
			}

			if ( ! $has_filter ) {
				return;
			}

			// --- Bot blocking ---
			// phpcs:ignore WordPress.Security.ValidatedSanitizedInput -- UA string compared against bot list, not output.
			$user_agent = $_SERVER['HTTP_USER_AGENT'] ?? '';

			if ( \LightweightPlugins\Firewall\Rules\BotBlocker::is_blocked( $user_agent ) ) {
				// Log if enabled.
				if ( ! empty( $options['log_enabled'] ) ) {
					\LightweightPlugins\Firewall\Logger::log(
						[
							'ip'     => \LightweightPlugins\Firewall\IpDetector::get_ip(),
							'reason' => 'bot_blocked',
							'ua'     => substr( $user_agent, 0, 200 ),
							// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
							'url'    => sanitize_url( wp_unslash( $_SERVER['REQUEST_URI'] ?? '' ) ),
						]
					);
				}

				\LightweightPlugins\Firewall\Rules\BotBlocker::block();
				return; // Never reached — block() calls exit.
			}

			// --- Rate limiting ---
			$ip = \LightweightPlugins\Firewall\IpDetector::get_ip();

			// Select storage backend.
			$storage_pref = $options['storage'] ?? 'auto';
			$storage      = null;

			if ( 'apcu' === $storage_pref && \LightweightPlugins\Firewall\Storage\ApcuStorage::is_available() ) {
				$storage = new \LightweightPlugins\Firewall\Storage\ApcuStorage();
			} elseif ( 'redis' === $storage_pref && \LightweightPlugins\Firewall\Storage\RedisStorage::is_available() ) {
				$storage = new \LightweightPlugins\Firewall\Storage\RedisStorage();
			} elseif ( 'file' === $storage_pref ) {
				$storage = new \LightweightPlugins\Firewall\Storage\FileStorage();
			}

			// Auto-detect: apcu > redis > file.
			if ( null === $storage ) {
				if ( \LightweightPlugins\Firewall\Storage\ApcuStorage::is_available() ) {
					$storage = new \LightweightPlugins\Firewall\Storage\ApcuStorage();
				} elseif ( \LightweightPlugins\Firewall\Storage\RedisStorage::is_available() ) {
					$storage = new \LightweightPlugins\Firewall\Storage\RedisStorage();
				} else {
					$storage = new \LightweightPlugins\Firewall\Storage\FileStorage();
				}
			}

			$rate_limiter = new \LightweightPlugins\Firewall\Rules\RateLimiter( $storage );

			if ( ! $rate_limiter->is_allowed( $ip ) ) {
				// Log if enabled.
				if ( ! empty( $options['log_enabled'] ) ) {
					\LightweightPlugins\Firewall\Logger::log(
						[
							'ip'     => $ip,
							'reason' => 'rate_limited',
							'ua'     => substr( $user_agent, 0, 200 ),
							// phpcs:ignore WordPress.Security.ValidatedSanitizedInput
							'url'    => sanitize_url( wp_unslash( $_SERVER['REQUEST_URI'] ?? '' ) ),
						]
					);
				}

				\LightweightPlugins\Firewall\Rules\RateLimiter::limit();
				return; // Never reached — limit() calls exit.
			}
		},
		1
	); // Priority 1 — run as early as possible.
} )();
